#指定运行环境
 language: node_js
 #指定nodejs版本，可以指定多个
 node_js:
   - 8

 before_script:
   - npm install should --save-dev
   - npm install -g mocha

 #保存node_modules
 cache : directories : - " node_modules" 
 script:
   - npm run test

 #指定分支，只有指定的分支提交时才会运行脚本
 branches:
   only:
     - master