language: node_js
# nodejs版本
node_js:
- '10'

# Travis-CI Caching
cache:
  directories:
  - node_modules


# S: Build Lifecycle
install:
- npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
- npm test

after_script:
- cd ./dist
- git init
- git config user.name "Sofiya-xuanxuan"
- git config user.email "570713531@qq.com"
- git add .
- git commit -m "Update tools"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
  - master
env:
  global:
  - GH_REF: https://github.com/Sofiya-xuanxuan/exercise2.git
