language: node_js
before_script:
  - npm install mocha
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
node_js:
  - '8'
script:
  - npm test