# before_install
# install
# before_script
# script
# aftersuccess or afterfailure
# [OPTIONAL] before_deploy
# [OPTIONAL] deploy
# [OPTIONAL] after_deploy
# after_script

language: node_js
install: npm install
before_script: 
      npm install mocha@5.2.0;
script: 
      mocha ./test/test.js