#指定运行环境
 before_script:
   - npm install -g mocha
   - npm install should --save-dev
 language: node_js
 #指定nodejs版本，可以指定多个
 node_js:
   - 8
 script:
   - npm run test

 #指定分支，只有指定的分支提交时才会运行脚本
 branches:
   only:
     - master