language: node_js
node_js:
  - "8"
script: mocha
before_install:
  - npm install
  - npm install -g mocha
  - npm install -g should
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start