# 使用的语言
language: node_js

# 使用的nodejs版本
node_js:
  - "8"

# 仓库的分支
branches:
  only:
  - master

# 执行isntall前需要执行的命令
before_install:
# 配置git 的个人信息
 - git config --global user.name 'arissy'
 - git config --global user.email 984385267@qq.com

# 执行install
install:
 - npm install mocha -g
 - npm install

# 执行命令脚本
script:
 - npm test